# Python Automation Mini Project
## Sales Orders Reporting Automation

في الـ notebook ده هنشتغل خطوة بخطوة على:
1. قراءة الداتا
2. فهم شكلها
3. تنظيفها
4. عمل Features
5. بناء Reports
6. حفظ النتائج
7. فهم فكرة Python Automation Scripts

**Dataset file:** `python_automation_sales_orders.csv`

## 1) Import Libraries

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

## 2) Read the Dataset

In [3]:
df = pd.read_csv("python_automation_sales_orders.csv")
df.head()

,order_id,order_date,customer_id,product_id,quantity,discount_pct,payment_method,delivery_days,returned_flag,customer_rating,customer_city,customer_age,customer_segment,product_category,product_name,unit_price,gross_revenue,net_revenue
0,50109,2024-10-10,1021,2007,5.0,0.0,Cash,4.0,0,4.0,tanta,33,Regular,Groceries,Olive Oil 7,2727.69,13638.45,13638.4500
1,50083,2024-12-31,1061,2014,3.0,5.0,card,8.0,0,2.0,Ismailia,24,Regular,Groceries,Olive Oil 14,2648.26,7944.78,7547.5410
2,50268,2024-10-20,1013,2017,4.0,0.0,Cash,8.0,0,NaN,ZAGAZIG,44,New,Groceries,Pasta 17,1437.71,5750.84,5750.8400
3,50070,2024-10-23,1075,2039,2.0,10.0,Card,6.0,0,1.0,ZAGAZIG,46,New,Electronics,Wireless Mouse 39,154.27,308.54,277.6860
4,51729,2024-11-21,1002,2027,1.0,5.0,BANK TRANSFER,8.0,0,NaN,SUEZ,24,VIP,sports,Jump Rope 27,3197.17,3197.17,3037.3115

## 3) First Look at the Data
نبدأ نفهم:
- عدد الصفوف والأعمدة
- أسماء الأعمدة
- أنواع البيانات
- Missing values

In [4]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nInfo:")
df.info()

print("\nMissing Values:")
print(df.isna().sum().sort_values(ascending=False))

Shape: (1414, 18)

Columns:
['order_id', 'order_date', 'customer_id', 'product_id', 'quantity', 'discount_pct', 'payment_method', 'delivery_days', 'returned_flag', 'customer_rating', 'customer_city', 'customer_age', 'customer_segment', 'product_category', 'product_name', 'unit_price', 'gross_revenue', 'net_revenue']

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1414 entries, 0 to 1413
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1414 non-null   int64
 1   order_date        1414 non-null   object
 2   customer_id       1414 non-null   int64
 3   product_id        1414 non-null   int64
 4   quantity          1414 non-null   float64
 5   discount_pct      1272 non-null   float64
 6   payment_method    1414 non-null   object
 7   delivery_days     1414 non-null   float64
 8   returned_flag     1414 non-null   int64
 9   customer_rating   1129 non-null   float64
 10  customer_city     1385 non-null   object
 11  customer_age      1414 non-null   int64
 12  customer_segment  1414 non-null   object
 13  product_category  1414 non-null   object
 14  product_name      1414 non-null   object
 15  unit_price        1400 non-null   float64
 16  gross_revenue     1400 non-null   float64
 17  net_revenue       1400 non-null   float64
dtypes: float64(7), int64(5), object(6)
memory usage: 199.0+ KB

Missing Values:
customer_rating     285
discount_pct        142
customer_city        29
gross_revenue        14
unit_price           14
net_revenue          14
payment_method        0
delivery_days         0
returned_flag         0
order_date            0
quantity              0
customer_age          0
customer_segment      0
product_category      0
product_name          0
product_id            0
customer_id           0
order_id              0
dtype: int64

In [5]:
df.describe()

,order_id,customer_id,product_id,quantity,discount_pct,delivery_days,returned_flag,customer_rating,customer_age,unit_price,gross_revenue,net_revenue
count,1414.000000,1414.000000,1414.000000,1414.000000,1272.000000,1414.000000,1414.000000,1129.000000,1414.000000,1400.000000,1400.000000,1400.000000
mean,50896.923621,1089.108204,2022.468175,2.917963,6.898585,3.941301,0.084866,3.702391,39.094767,1651.017143,4764.022557,4488.364055
std,517.960589,52.576157,12.801165,1.471716,8.505097,2.652047,0.278780,1.164640,12.134342,1038.117601,4127.721695,3953.484791
min,50001.000000,1001.000000,2001.000000,-1.000000,0.000000,-2.000000,0.000000,1.000000,18.000000,57.160000,-2917.620000,-2727.690000
25%,50431.500000,1045.000000,2011.000000,2.000000,0.000000,2.000000,0.000000,3.000000,29.000000,491.950000,1475.850000,1349.148000
50%,50866.500000,1088.500000,2022.000000,3.000000,5.000000,4.000000,0.000000,4.000000,39.000000,1898.900000,3331.650000,3161.413750
75%,51356.500000,1135.000000,2033.000000,4.000000,10.000000,6.000000,0.000000,5.000000,49.000000,2648.260000,7718.040000,7012.851750
max,51798.000000,1180.000000,2045.000000,5.000000,30.000000,8.000000,1.000000,5.000000,60.000000,3197.170000,15985.850000,15985.850000

## 4) Convert Data Types
- `order_date` → datetime
- الأعمدة الرقمية → numeric

In [6]:
df["order_date"] = pd.to_datetime(df["order_date"], format="%Y-%m-%d", errors="coerce")

numeric_cols = ["quantity", "discount_pct", "delivery_days", "customer_rating", "unit_price"]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1414 entries, 0 to 1413
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          1414 non-null   int64
 1   order_date        1414 non-null   datetime64[ns]
 2   customer_id       1414 non-null   int64
 3   product_id        1414 non-null   int64
 4   quantity          1414 non-null   float64
 5   discount_pct      1272 non-null   float64
 6   payment_method    1414 non-null   object
 7   delivery_days     1414 non-null   float64
 8   returned_flag     1414 non-null   int64
 9   customer_rating   1129 non-null   float64
 10  customer_city     1385 non-null   object
 11  customer_age      1414 non-null   int64
 12  customer_segment  1414 non-null   object
 13  product_category  1414 non-null   object
 14  product_name      1414 non-null   object
 15  unit_price        1400 non-null   float64
 16  gross_revenue     1400 non-null   float64
 17  net_revenue       1400 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(5), object(5)
memory usage: 199.0+ KB

## 5) Text Cleaning
هننضف الأعمدة النصية من:
- المسافات الزائدة
- اختلاف الـ case

In [7]:
def clean_text(value):
    if pd.isna(value):
        return value
    return str(value).strip().title()

text_cols = ["payment_method", "customer_city", "product_category", "customer_segment", "product_name"]

for col in text_cols:
    df[col] = df[col].apply(clean_text)

df[text_cols].head()

,payment_method,customer_city,product_category,customer_segment,product_name
0,Cash,Tanta,Groceries,Regular,Olive Oil 7
1,Card,Ismailia,Groceries,Regular,Olive Oil 14
2,Cash,Zagazig,Groceries,New,Pasta 17
3,Card,Zagazig,Electronics,New,Wireless Mouse 39
4,Bank Transfer,Suez,Sports,Vip,Jump Rope 27

## 6) Remove Duplicates

In [10]:
df.duplicated().sum()

14

In [11]:
before = len(df)
df = df.drop_duplicates()
#==== df.drop_duplicates(inplace=True) --- IGNORE ---
after = len(df)

print("Duplicates removed:", before - after)
print("Shape after removing duplicates:", df.shape)

Duplicates removed: 14
Shape after removing duplicates: (1400, 18)

## 7) Handle Missing Values
### Business Logic:
- `discount_pct` missing → 0
- `customer_city` missing → `"Unknown"`
- `customer_rating` missing → median
- `unit_price` missing → median by category, then overall median

In [12]:
df.isnull().sum()

order_id              0
order_date            0
customer_id           0
product_id            0
quantity              0
discount_pct        140
payment_method        0
delivery_days         0
returned_flag         0
customer_rating     280
customer_city        28
customer_age          0
customer_segment      0
product_category      0
product_name          0
unit_price           14
gross_revenue        14
net_revenue          14
dtype: int64

In [13]:
df["discount_pct"] = df["discount_pct"].fillna(0)
df["customer_city"] = df["customer_city"].fillna("Unknown")
df["customer_rating"] = df["customer_rating"].fillna(df["customer_rating"].median())

df["unit_price"] = df.groupby("product_category")["unit_price"].transform(lambda s: s.fillna(s.median()))
#df["unit_price"] = df["unit_price"].fillna(df["unit_price"].median())

df.isna().sum().sort_values(ascending=False)

C:\Users\abdel\AppData\Local\Temp\ipykernel_2444\2844133765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["discount_pct"] = df["discount_pct"].fillna(0)
C:\Users\abdel\AppData\Local\Temp\ipykernel_2444\2844133765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["customer_city"] = df["customer_city"].fillna("Unknown")
C:\Users\abdel\AppData\Local\Temp\ipykernel_2444\2844133765.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["customer_rating"] = df["customer_rating"].fillna(df["customer_rating"].median())
C:\Users\abdel\AppData\Local\Temp\ipykernel_2444\2844133765.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["unit_price"] = df.groupby("product_category")["unit_price"].transform(lambda s: s.fillna(s.median()))

net_revenue         14
gross_revenue       14
order_date           0
unit_price           0
product_name         0
product_category     0
customer_segment     0
customer_age         0
customer_city        0
order_id             0
returned_flag        0
delivery_days        0
payment_method       0
discount_pct         0
quantity             0
product_id           0
customer_id          0
customer_rating      0
dtype: int64

## 8) Handle Invalid Values
### Rules:
- `quantity <= 0` تعتبر invalid
- `delivery_days < 0` تعتبر invalid

In [22]:
df.loc[df["quantity"] <= 0, "quantity"] = np.nan
df.loc[df["delivery_days"] < 0, "delivery_days"] = np.nan

df.isnull().sum().sort_values(ascending=False)

net_revenue         13
gross_revenue       13
order_date           0
unit_price           0
product_name         0
product_category     0
customer_segment     0
customer_age         0
customer_city        0
order_id             0
returned_flag        0
delivery_days        0
payment_method       0
discount_pct         0
quantity             0
product_id           0
customer_id          0
customer_rating      0
dtype: int64

In [21]:
df.dropna(subset=["quantity", "delivery_days"], inplace=True)

df.isnull().sum().sort_values(ascending=False)

net_revenue         13
gross_revenue       13
order_date           0
unit_price           0
product_name         0
product_category     0
customer_segment     0
customer_age         0
customer_city        0
order_id             0
returned_flag        0
delivery_days        0
payment_method       0
discount_pct         0
quantity             0
product_id           0
customer_id          0
customer_rating      0
dtype: int64

## 9) Feature Engineering
هنضيف:
- `month`
- `gross_revenue`
- `net_revenue`

In [24]:
df["month"] = df["order_date"].dt.month_name()
df["gross_revenue"] = df["unit_price"] * df["quantity"]
df["net_revenue"] = df["gross_revenue"] * (1 - df["discount_pct"] / 100)

df[["order_date", "month", "unit_price", "quantity", "gross_revenue", "net_revenue"]].head()

  order_date     month  unit_price  quantity  gross_revenue  net_revenue
0 2024-10-10   October     2727.69       5.0       13638.45   13638.4500
1 2024-12-31  December     2648.26       3.0        7944.78    7547.5410
2 2024-10-20   October     1437.71       4.0        5750.84    5750.8400
3 2024-10-23   October      154.27       2.0         308.54     277.6860
4 2024-11-21  November     3197.17       1.0        3197.17    3037.3115

In [25]:
df.to_csv("python_automation_sales_orders_cleaned.csv", index=False)

## 10) KPI Summary

In [ ]:
total_orders = df["order_id"].nunique()
total_customers = df["customer_id"].nunique()
total_revenue = round(df["net_revenue"].sum(), 2)
avg_order_value = round(df.groupby("order_id")["net_revenue"].sum().mean(), 2)
return_rate = round(df["returned_flag"].mean() * 100, 2)
avg_delivery_days = round(df["delivery_days"].mean(), 2)

kpi_summary = pd.DataFrame({
    "metric": [
        "total_orders",
        "total_customers",
        "total_net_revenue",
        "average_order_value",
        "return_rate_pct",
        "avg_delivery_days"
    ],
    "value": [
        total_orders,
        total_customers,
        total_revenue,
        avg_order_value,
        return_rate,
        avg_delivery_days
    ]
})

kpi_summary

## 11) Revenue by Category

In [ ]:
revenue_by_category = (
    df.groupby("product_category", as_index=False)
      .agg(
          total_net_revenue=("net_revenue", "sum"),
          total_quantity=("quantity", "sum"),
          avg_rating=("customer_rating", "mean")
      )
      .sort_values("total_net_revenue", ascending=False)
)

revenue_by_category.head(10)

## 12) Revenue by City

In [ ]:
revenue_by_city = (
    df.groupby("customer_city", as_index=False)
      .agg(
          total_net_revenue=("net_revenue", "sum"),
          total_orders=("order_id", "nunique"),
          avg_delivery_days=("delivery_days", "mean")
      )
      .sort_values("total_net_revenue", ascending=False)
)

revenue_by_city.head(10)

## 13) Monthly Sales Report

In [ ]:
monthly_sales = (
    df.groupby("month", as_index=False)
      .agg(
          total_net_revenue=("net_revenue", "sum"),
          total_orders=("order_id", "nunique"),
          return_rate=("returned_flag", "mean")
      )
      .sort_values("month")
)

monthly_sales["return_rate_pct"] = (monthly_sales["return_rate"] * 100).round(2)

monthly_sales

## 14) Returned Orders Report

In [ ]:
returned_orders = df[df["returned_flag"] == 1].copy()
returned_orders = returned_orders[[
    "order_id", "order_date", "customer_id", "customer_city",
    "product_category", "product_name", "net_revenue", "delivery_days"
]].sort_values(["order_date", "order_id"])

returned_orders.head(10)

## 15) Top Products

In [ ]:
top_products = (
    df.groupby(["product_id", "product_name", "product_category"], as_index=False)
      .agg(
          total_net_revenue=("net_revenue", "sum"),
          total_quantity=("quantity", "sum")
      )
      .sort_values("total_net_revenue", ascending=False)
      .head(15)
)

top_products

## 16) Export Reports to CSV

In [ ]:
output_path = Path("automation_reports")
output_path.mkdir(exist_ok=True)

df.to_csv(output_path / "cleaned_sales_orders.csv", index=False)
kpi_summary.to_csv(output_path / "kpi_summary.csv", index=False)
revenue_by_category.to_csv(output_path / "revenue_by_category.csv", index=False)
revenue_by_city.to_csv(output_path / "revenue_by_city.csv", index=False)
monthly_sales.to_csv(output_path / "monthly_sales.csv", index=False)
returned_orders.to_csv(output_path / "returned_orders.csv", index=False)
top_products.to_csv(output_path / "top_products.csv", index=False)

print("CSV reports exported successfully.")

## 17) Export Reports to Excel (Multiple Sheets)

In [ ]:
with pd.ExcelWriter(output_path / "sales_report.xlsx", engine="openpyxl") as writer:
    kpi_summary.to_excel(writer, sheet_name="KPI Summary", index=False)
    revenue_by_category.to_excel(writer, sheet_name="By Category", index=False)
    revenue_by_city.to_excel(writer, sheet_name="By City", index=False)
    monthly_sales.to_excel(writer, sheet_name="Monthly Sales", index=False)
    top_products.to_excel(writer, sheet_name="Top Products", index=False)
    returned_orders.to_excel(writer, sheet_name="Returned Orders", index=False)

print("Excel report exported successfully.")

## 18) Why This Is Automation?
بدل ما نعمل نفس الخطوات يدويًا كل مرة:
- نقرأ الملف
- ننضفه
- نحسب KPIs
- نطلع تقارير
- نصدر النتائج

إحنا قدرنا نكتبهم كـ **pipeline واضحة**.  
والخطوة اللي بعدها إننا نحط نفس الكلام جوه **`.py script`** ونشغله بأمر واحد.

## 19) Final Challenge for Students
جرّب تضيف واحد من التقارير دي:
1. Revenue by `payment_method`
2. Revenue by `customer_segment`
3. Top 10 cities by revenue
4. Monthly average rating